development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: petpassteam@gmail.com
  :password: "Change!23"
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: petpassteam@gmail.com
  :password: "Change!23"
  :enable_starttls_auto: true
  # :user_name: petpassteam@gmail.com
  # :password: "Change!23"
  # :domain: hoos.in
  # :address: smtp.sendgrid.net
  # :port: 587
  # :authentication: plain
  # :enable_starttls_auto: true